server {
    # On écoute uniquement sur le port 443 en IPv4 et IPv6
    listen 443 ssl;
    listen [::]:443 ssl;

    # Ton nom de domaine
    server_name ahamini.42.fr;

    # Les chemins vers ton certificat SSL (généré dans le Dockerfile)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Les protocoles de sécurité exigés par le sujet 42
    ssl_protocols TLSv1.2 TLSv1.3;

    # Le dossier où se trouvent les fichiers du site et le fichier par défaut
    root /var/www/wordpress;
    index index.php index.html index.htm;

    # Si on cherche une page qui n'existe pas, on renvoie une erreur 404
    location / {
        try_files $uri $uri/ =404;
    }

    # C'est ici que la magie opère pour lire le PHP !
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # On renvoie la requête vers le conteneur 'wordpress' sur le port 9000
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}