[www]
user = www-data
group = www-data

# On force PHP-FPM à écouter sur le port 9000 (et non sur un socket Unix)
listen = 9000
listen.owner = www-data
listen.group = www-data

# Gestion des processus
pm = dynamic
pm.max_children = 25
pm.start_servers = 5
pm.min_spare_servers = 1
pm.max_spare_servers = 10

# TRÈS IMPORTANT : Autorise PHP à lire les variables du fichier .env
clear_env = no